#!/usr/bin/env bash

#
# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------
#
# Written by Giorgio Desideri <giorgio.desideri@gmail.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#
# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------
#

# set root password to not type any time
password="YourRootPassword"

# Print memory status = BEFORE
expect <<- DONE
	set timeout -1

	spawn su root -c free
	match_max 100000

	# Look for passwod prompt
	expect "*?assword:*"
  
	# Send password aka $password
  	send -- "$password\r"
  
  	expect eof
DONE


# Free memory
expect <<- DONE
        set timeout -1

        spawn su root -c "sync; echo 3 > /proc/sys/vm/drop_caches"
        match_max 100000

        # Look for passwod prompt
        expect "*?assword:*"
  
        # Send password aka $password
        send -- "$password\r"
  
        expect eof
DONE

# Print memory status - AFTER
expect <<- DONE
        set timeout -1

        spawn su root -c free
        match_max 100000

        # Look for passwod prompt
        expect "*?assword:*"
  
        # Send password aka $password
        send -- "$password\r"
  
        expect eof
DONE

printf "\n\t Hey man, That's All Folks !!! \n"

exit
